version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stock-control-db
    environment:
      POSTGRES_DB: stock_control
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: usertest123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
